export const RICE_COLORS = {
  Basmati: "#FF5733",
  Gonen: "#33FF57",
  Ipsala: "#5733FF",
  Jasmine: "#33FFFF",
  Karacadag: "#FF33F6",
}

export const MODEL_OPTIONS = [
  { value: "knn", label: "K-Nearest Neighbors" },
  { value: "svm", label: "Support Vector Machine" },
  { value: "nb", label: "Naive Bayes" },
]

export const FEATURE_GROUPS = {
  Basic: [
    "AREA",
    "PERIMETER",
    "MAJOR_AXIS",
    "MINOR_AXIS",
    "ECCENTRICITY",
    "EQDIASQ",
    "SOLIDITY",
    "CONVEX_AREA",
    "EXTENT",
    "ASPECT_RATIO",
    "ROUNDNESS",
    "COMPACTNESS",
  ],
  ShapeFactors: ["SHAPEFACTOR_1", "SHAPEFACTOR_2", "SHAPEFACTOR_3", "SHAPEFACTOR_4"],
  RGB: [
    "meanRR",
    "meanRG",
    "meanRB",
    "StdDevRR",
    "StdDevRG",
    "StdDevRB",
    "skewRR",
    "skewRG",
    "skewRB",
    "kurtosisRR",
    "kurtosisRG",
    "kurtosisRB",
    "entropyRR",
    "entropyRG",
    "entropyRB",
  ],
  HSV: [
    "meanH",
    "meanS",
    "meanV",
    "StdDevH",
    "StdDevS",
    "StdDevV",
    "skewH",
    "skewS",
    "skewV",
    "kurtosisH",
    "kurtosisS",
    "kurtosisV",
    "entropyH",
    "entropyS",
    "entropyV",
  ],
  LAB: [
    "meanL",
    "meanA",
    "meanB",
    "StdDevL",
    "StdDevA",
    "StdDevB",
    "skewL",
    "skewA",
    "skewB",
    "kurtosisL",
    "kurtosisA",
    "kurtosisB",
    "entropyL",
    "entropyA",
    "entropyB",
  ],
  YCbCr: [
    "meanY",
    "meanCb",
    "meanCr",
    "StdDevY",
    "StdDevCb",
    "StdDevCr",
    "skewY",
    "skewCb",
    "skewCr",
    "kurtosisY",
    "kurtosisCb",
    "kurtosisCr",
    "entropyY",
    "entropyCb",
    "entropyCr",
  ],
  XYZ: [
    "meanXX",
    "meanYY",
    "meanZZ",
    "StdDevXX",
    "StdDevYY",
    "StdDevZZ",
    "skewXX",
    "skewYY",
    "skewZZ",
    "kurtosisXX",
    "kurtosisYY",
    "kurtosisZZ",
    "entropyXX",
    "entropyYY",
    "entropyZZ",
  ],
  Wavelet: [
    "ALLdaub4RR",
    "ALLdaub4RG",
    "ALLdaub4RB",
    "ALLdaub4H",
    "ALLdaub4S",
    "ALLdaub4V",
    "ALLdaub4L",
    "ALLdaub4a",
    "ALLdaub4b",
    "ALLdaub4Y",
    "ALLdaub4Cb",
    "ALLdaub4Cr",
    "ALLdaub4XX",
    "ALLdaub4YY",
    "ALLdaub4ZZ",
  ],
} 